import json
import struct
from pathlib import Path
from disc import write_if_changed
import tundra_spawner
def add_items(stage, profile, overlay, dat_dir, output_dir):
	import models
	offset = lambda pointer: 48 + pointer - 0x800E7000; pointer = struct.unpack_from("<I", overlay, offset(0x800F0ED4 if stage == "ST0D" else 0x80100E30))[0]; items = []
	if stage == "ST0D":
		sources = [record for record in profile["exterior_enemies"] if record["actor_class"] == 21]; profile["exterior_enemies"] = [record for record in profile["exterior_enemies"] if record["actor_class"] != 21]
		profile["item_models"] = [model for model in profile["models"] if any(model["model_index"] == record["model_index"] for record in sources)]
	else:
		npcs = json.loads((output_dir / stage / "npcs.json").read_text(encoding="utf-8")); sources = []; archive, payload = models.actor_archive(dat_dir / "ST0F00.BIN"); match = next(model for model in archive["models"] if model["flags"] & 65535 == 0x1520); model = models.export_actor_model(payload, match["index"], dat_dir / "ST0FT.BIN", output_dir / stage / "actors/mine_chest.glb", "ST0F00.BIN"); model.update(model_index=match["index"], model_file="actors/mine_chest.glb"); profile["item_models"] = [model]
		for record in npcs["static_actor_instances"]:
			raw = bytes.fromhex(record["source_bytes_hex"])
			if raw[4] == 21: sources.append(dict(record, stage=stage, actor_class=21, dispatch_index=raw[6], model_file="actors/mine_chest.glb", model_index=match["index"]))
	for record in sources:
		raw = bytes.fromhex(record["source_bytes_hex"]); flag, message, reward = struct.unpack_from("<HHI", overlay, offset(pointer + raw[6] * 8)); body = 0x800F0ED8 if stage == "ST0D" else 0x80100E34; target = 0x800F0EE4 if stage == "ST0D" else 0x80100E40; record["native_hitbox"] = {"bounds_raw": list(struct.unpack_from("<6h", overlay, offset(body)))}; record["native_interaction"] = {"stage": stage, "message_index": message, "message_call": "0x800BE330", "request_kind": 0, "target_descriptor_raw": list(struct.unpack_from("<6h", overlay, offset(target))), "target_flags60": 1, "target_criteria": {"range_extra_raw": 192, "yaw_half_cone_raw": 384, "strict_bounds": True}}; record["startup_control"] = {"code": 0}; items.append({"entry": record, "collected_flag": flag, "message_index": message, "reward_word": reward, "descriptor_ram": hex(pointer + raw[6] * 8), "source_callback": "0x800EB760" if stage == "ST0D" else "0x800EEEEC"})
	profile["items"] = items
	for item in items:
		item["entry"]["native_interaction"]["bank_id"] = "0x8010C000"; item["entry"]["native_interaction"]["target_criteria"]["line_of_sight"] = False
	if stage == "ST0D":
		models.export_pickup_data((dat_dir.parent / "COMMON/GAME.BIN").read_bytes(), output_dir / stage)
		for record in profile["exterior_enemies"]:
			record["native_hitbox"] = {"bounds_raw": list(struct.unpack_from("<6h", overlay, offset(0x800F0F50)))}; record["native_target_bounds"] = list(struct.unpack_from("<6h", overlay, offset(0x800F0F5C))); record["behavior_dispatch"].update(constructor="0x800ED698", state_callbacks=["0x800ED86C", "0x800ED8DC", "0x800EDC58", "0x800EDE3C", "0x800EDECC"], hit_callback="0x800EE51C", death_callback="0x800EE45C"); record["native_health_scale"] = 1
def export(dat_dir, output_dir):
	import models
	import world
	dat_dir = Path(dat_dir); output_dir = Path(output_dir); game = (dat_dir.parent / "COMMON/GAME.BIN").read_bytes(); result = {}
	for stage in ("ST0D", "ST0F"):
		overlay = (dat_dir / f"{stage}T.BIN").read_bytes(); offset = lambda pointer: 48 + pointer - 0x800E7000; instances = []; model_list = []
		if stage == "ST0D":
			definitions = [(0, 0x800F0020, 0x800ED490), (0, 0x800F0034, 0x800ED490), (1, 0x800F0084, None)]; records = [{"raw": overlay[offset(pointer):offset(pointer) + 20]} for _, pointer, _ in definitions]; archive = world.actor_archive_for_records(stage, (dat_dir / f"{stage}.BIN").read_bytes(), records, models.ROOT / "build/stages", dat_dir, 0xB000); exported = {}
			for area, pointer, callback in definitions:
				raw = overlay[offset(pointer):offset(pointer) + 20]; actor_class = raw[4]; matches = [entry for entry in archive["archive"]["models"] if entry["flags"] & 0xFFFF == (actor_class << 8 | 0x20)]
				if len(matches) != 1: raise ValueError(f"{stage} class{actor_class:02X} model selector is unresolved")
				index = matches[0]["index"]; model_file = f"actors/{stage}_model_{index:02d}.glb"
				if index not in exported:
					model = models.export_actor_model(archive["payload"], index, dat_dir / f"{stage}T.BIN", output_dir / stage / model_file, archive["archive_file"]); model.update(model_index=index, model_file=model_file, native_resource_flags=matches[0]["flags"]); exported[index] = model; model_list.append(model)
				x, y, z, yaw = struct.unpack_from("<hhhH", raw, 12); combat = models.source_combat_attributes(game, actor_class, raw[7]); instances.append({"stage": stage, "area_index": area, "source_record_ram": hex(pointer), "source_bytes_hex": raw.hex(), "actor_class": actor_class, "dispatch_index": raw[6], "actor_resource_key": raw[7], "model_index": index, "model_file": model_file, "transform_raw": [x, y, z, yaw], "transform": {"position": [-x / 256, -y / 256, z / 256], "yaw_turns": -yaw / 4096}, "combat": combat, "source_attributes": combat["normal"]["attributes"], "behavior_dispatch": {"actor_class": actor_class, "class_callback": hex(callback) if callback else None}, "source": {"loader": "SLES8003D3F8", "area_table": "ST0DT800F00AC", "spawn_gate": "static area list; no quest flag predicate"}})
			profile = {"stage": stage, "tick_rate": 25, "entrance": {"source_transform_raw": [13056, -1632, -2304, 3072], "destination_stage": "ST0F", "destination_area": 0, "destination_transform_raw": [-2304, -1, 512, 3072], "route_pointer_ram": "0x800F0308", "native_lock_event": 0x710, "source": "ST0DT route table800F0370; GAME800B89B4 lock consumer", "source_contact_unresolved": True}, "exterior_enemies": instances, "models": model_list}
		else:
			row = struct.unpack_from("<I", overlay, offset(0x801008F4))[0]; handlers = list(struct.unpack_from("<13I", overlay, offset(row))); scene_ids = [0x50, 0x51, 0x52, 0x53, 0x54]; actor_records = []
			for pointer in (0x801007EC, 0x80100800, 0x80100814, 0x80100828, 0x8010083C, 0x80100850, 0x80100864, 0x80100878):
				raw = overlay[offset(pointer):offset(pointer) + 20]; actor_records.append({"source_record_ram": hex(pointer), "source_bytes_hex": raw.hex(), "actor_class": raw[4], "record_type": raw[2], "transform_raw": list(struct.unpack_from("<hhhH", raw, 12))})
			profile = {"stage": stage, "tick_rate": 25, "scenario0_area_callbacks": [hex(pointer) for pointer in handlers], "scene_ids": scene_ids, "records": actor_records, "quest_flags": {"intro": 0x580, "pre_boss": 0x581, "battle_started": 0x582, "boss_defeated": 0x583, "return_scene": 0x584, "entrance_initialized": 0x585}, "intro": {"area": 1, "native_x_minimum": 3072, "flag": 0x580, "scene": 0x50, "source": "ST0FT800E76F4..7714"}, "pre_boss": {"area": 11, "scene": 0x51, "flag": 0x581, "source": "ST0FT800E7738..7808"}, "boss": {"area": 12, "scene_start": 0x52, "scene_defeat": 0x53, "actor_pointer_ram": "0x8009C900", "actor_pointer_writer": "ST0FT800FE880..FE888 copies scene-owner+2C", "actor_record_ram": "0x80100850", "actor_class": 0x6F, "class_callback": "0x800F1E2C", "death_test": "signed16(actor+70)<0", "source": "ST0FT800E780C..78E4"}, "return": {"area": 11, "requires_set": 0x583, "requires_clear": 0x584, "flag_set": 0x584, "scene": 0x54, "source": "ST0FT800E7768..77AC"}, "entry_actions": {"area": 0, "first_visit_set": [0x783, 0x585], "first_visit_records": ["0x801007EC", "0x80100800"], "every_entry_clear": [0x5D0, *range(0x710, 0x730)], "source": "ST0FT800E7574..7600"}}
		if stage == "ST0D":
			terrain = world.Stage((dat_dir / "ST0D.BIN").read_bytes()); tiles, _ = terrain.area(0); _, model_id, _, height, x, z = terrain.placements[67]; _, header, directory = terrain.directories[model_id]; variant = terrain.base + (directory & 65535) * 4 + 12; pointer = struct.unpack_from("<H", terrain.data, variant)[0]; groups = terrain.model(pointer); ox = (x << 9) - (0x7E00 if header & 0x10000000 else 0x7F00); oz = (z << 9) - (0x7E00 if header & 0x20000000 else 0x7F00); oy = 0x400 - tiles[(x, z)][6] * 16 - ((height & 0x7F00) >> 4); vram, _ = world.textures(dat_dir / "ST0DT.BIN"); glb = world.Glb(vram); glb.instance("placement_067_model_015", pointer, groups, [-ox / 256, -oy / 256, oz / 256], terrain.face_metadata[pointer]); glb.save(output_dir / stage / "mine_entrance_open.glb"); collision_pointer = struct.unpack_from("<H", terrain.data, variant + 2)[0] * 4 + terrain.base; boxes = []
			for index in range(terrain.data[variant + 6]):
				address = collision_pointer + index * 16; values = struct.unpack_from("<6h2H", terrain.data, address); boxes.append({"x": [values[0] + ox, values[1] + ox], "z": [values[2] + oz, values[3] + oz], "y": [values[4] + oy, values[5] + oy], "kind": values[6], "mask": values[7], "placement": 67, "source_offset": hex(address), "contact_raw": [(values[0] + values[1]) // 2 + ox, (values[4] + values[5]) // 2 + oy, (values[2] + values[3]) // 2 + oz]})
			contact = next(box for box in boxes if box["kind"] >> 8 == 15); contact.update(type=15, automatic=True, probe_forward_raw=0, source_consumer="GAME800B8588;type15:800B8134->800B8460"); doors = json.loads((output_dir / stage / "doors.json").read_text(encoding="utf-8")); walk = next(route["native_automatic_walk"] for route in doors["area_transitions"] if route.get("native_automatic_walk")); profile["entrance"].update(availability={"any": [{"kind": "stage_state_byte_not_equals", "value": 0}, {"kind": "native_event_flag", "id": 0x5E1, "set": True}, {"kind": "native_event_flag", "id": 0x5E2, "set": True}]}, placement=67, model_variant=1, model_file="mine_entrance_open.glb", collision_boxes=boxes, native_contacts=[contact], native_automatic_walk=walk, source_contact_unresolved=False, source_variant="ST0DT800EEA3C..EEB14 GAME800C010C sets variant1 for placement cell89,59")
		else:
			pointer = 0x8010180C; raw = overlay[offset(pointer):offset(pointer) + 20]; profile["records"].append({"source_record_ram": hex(pointer), "source_bytes_hex": raw.hex(), "actor_class": raw[4], "record_type": raw[2], "transform_raw": list(struct.unpack_from("<hhhH", raw, 12))}); callback_row = struct.unpack_from("<I", overlay, offset(0x800FF4E0 + 7 * 4))[0]; callback = struct.unpack_from("<I", overlay, offset(callback_row))[0]; profile["boss"].update(actor_class=7, actor_record_ram=hex(pointer), record_type=0x20, class_callback=hex(callback), registration_command_ram="0x80101890", registration_slot=0); profile["item_gate"] = {"area": 8, "event_flag": 0x2B3, "helper": "SLES800464B4", "set_mode": 8, "clear_mode": 7, "source": "ST0FT800E7498..752C"}; profile["intro"]["native_states"] = [{"state": 0, "actions": [{"clear_pointer": "0x8009C904"}, {"next_state": 1}]}, {"state": 1, "context_must_be_inactive": True, "flag580_set_record": "0x8010083C", "flag580_set_next_state": 2, "flag580_clear_flag689_clear_record": "0x80100814", "flag580_clear_flag689_clear_set": 0x689, "flag580_clear_flag689_set_record": "0x80100828", "source": "ST0FT800E7660..76F0"}, {"state": 2, "native_x_minimum": 3072, "set_flag": 0x580, "scene": 0x50, "next_state": 3}]
		if stage == "ST0F":
			profile["intro"]["native_states"][1].update(flag580_set_next_state=3, flag580_clear_next_state=2); profile["roll_routes"] = {}
			for record, table, count in [(0x801007EC, 0x80100F0C, 6), (0x80100814, 0x80100F3C, 5)]: profile["roll_routes"][hex(record)] = {"points_raw": [list(struct.unpack_from("<4h", overlay, offset(table) + index * 8)) for index in range(count)], "table_ram": hex(table), "callback": "0x800F1538/0x800F1684", "speed_raw": 608, "turn_raw": 56, "terminal_turn_raw": 128, "arrival_box_half_extent_raw": 32}
			profile["roll_target"] = {"bounds_raw": list(struct.unpack_from("<6h", overlay, offset(0x80100F00))), "source": "ST0FT80100F00;constructorF128C", "flags60": 1}
			profile["refractor"] = {"actor_record_ram": "0x80100850", "actor_class": 0x6F, "callback": "0x800F1A8C", "constructor": "0x800F1BC8", "interaction_callback": "0x800F1CEC", "request_call": "0x800F1D90", "request_kind": 0x12, "message_index": 30, "target_bounds_raw": list(struct.unpack_from("<6h", overlay, offset(0x80100F90))), "body_bounds_raw": list(struct.unpack_from("<6h", overlay, offset(0x80100F84))), "yaw_step_raw": 16, "scale_raw": 1024, "boss_defeated_redirect": {"flag": 0x583, "message": 34, "tail_message": 35, "clear_flag": 0x710}, "native_bob": {"callback": "0x800F1B2C..1B6C", "table_ram": "0x800965D8", "table_count": 64, "sample_shift": 8, "sample_bias": -8, "samples_bound": False}, "source": "ST0FT PBDcallbacktable800FF4E0[class6F]->800FF4DC->800F1A8C;message30redirects583to34then35clears710"}
			executable = (dat_dir.parent / "SLES_035.56").read_bytes(); profile["refractor"]["native_bob"].update(samples_bound=True, samples_raw=[struct.unpack_from("<h", executable, 0x800 + 0x80073E4E - 0x80010000 + phase * 64 * 4)[0] for phase in range(64)], initializer="SLES800112B8..11314 copiescosinefrom80073E4E every64phases into800965D8")
			raw = overlay[offset(0x80100800):offset(0x80100800) + 20]; profile["procedural_actors"] = [{"stage": "ST0F", "area_index": 0, "source_record_ram": "0x80100800", "record_type": raw[2], "actor_class": raw[4], "source_bytes_hex": raw.hex(), "callback": "0x800FAA44", "dispatch": raw[6], "message_index": struct.unpack_from("<h", raw, 8)[0], "window": 4, "bank_id": "0x8010C000", "message_call": "0x800FB124", "maximum_scenario": struct.unpack_from("<b", raw, 10)[0], "skip_when_flag_set": struct.unpack_from("<h", raw, 18)[0], "message_source": "ST0FT800FB0FC..FB148 configureswindow4andcalls80048474 withsignedactor+0C;recordsource80100800", "source_dispatch": "SLES8003D010 scriptpool->ST0FT800FF784[0x1B]=800FAA44;subtype0table80101344[0]=800FAB48->800FB0FC"}]
		if stage == "ST0D": tundra_spawner.add(profile, overlay, game, dat_dir, output_dir, archive)
		add_items(stage, profile, overlay, dat_dir, output_dir); profile["source"] = {"overlay_sha256": world.sha256(overlay), "original_overlay": f"DAT/{stage}T.BIN"}; target = output_dir / stage / "mine_quest.json"; write_if_changed(target, json.dumps(profile, indent=2) + "\n", encoding="utf-8"); result[stage] = profile
	return result
if __name__ == "__main__": export(Path("build/disc-assets/DAT"), Path("assets/levels"))
