import json
import struct
from pathlib import Path
from disc import write_if_changed
from world import sha256
def add_to_manifest(manifest, dat_dir, output_dir):
	import models
	import world
	dat_dir = Path(dat_dir); output_dir = Path(output_dir); overlay = (dat_dir / "ST0DT.BIN").read_bytes(); root = (dat_dir / "ST0D.BIN").read_bytes(); offset = lambda address: 48 + address - 0x800E7000; pointer = 0x800F0FD8; raw = overlay[offset(pointer):offset(pointer) + 20]
	if raw.hex() != "03002002600000000000000000d5cafbd0ee0000": raise ValueError("ST0D native Roll record changed")
	if struct.unpack_from("<I", overlay, offset(0x800EFC34))[0] != 0x800EB9BC: raise ValueError("ST0D Roll callback changed")
	work = models.ROOT / "build/stages"; archive = world.actor_archive_for_records("ST0D", root, [{"raw": raw}], work, dat_dir, 0xB000)
	if archive is None: raise ValueError("ST0D Roll model archive missing")
	match = [entry for entry in archive["archive"]["models"] if entry["flags"] & 0xFFFFFF == 0x6020]
	if len(match) != 1 or match[0]["index"] != 9: raise ValueError("ST0D Roll model identity changed")
	model_file = "actors/ST0D_model_09.glb"; (output_dir / "actors").mkdir(parents=True, exist_ok=True); model = models.export_actor_model(archive["payload"], 9, dat_dir / "ST0DT.BIN", output_dir / model_file, archive["archive_file"])
	model.update(model_index=9, model_file=model_file, native_resource_flags=0x6020, native_scale_raw=list(struct.unpack_from("<3h", archive["payload"], match[0]["mesh_offset"] + 0x30)), identity="Roll", role="roll_companion")
	set_id = "native_tundra_roll_follower"; predicates = [{"kind": "stage_state_byte_equals", "value": 0}, {"kind": "stage_area_byte_equals", "value": 0}, {"kind": "native_event_flag", "id": 0x5E1, "set": True}, {"kind": "native_event_flag", "id": 0x5E2, "set": False}]
	spawn = {"id": set_id, "area_index": 0, "predicate": {"all": predicates}, "source": {"file": "ST0DT.BIN", "call_pc": "0x800eeb24", "callback": "0x800eea1c", "consumer": "ST0DT800EEE54 -> SLES8003E5B0; GAME800DA49C/800DA4E8", "native_side_effects": [], "native_local_state_mutations": []}, "record_offsets": [offset(pointer)], "non_mesh_records": []}
	x, y, z, yaw = struct.unpack_from("<hhhH", raw, 12); cases = [{"player_xz": [13824, -4864], "actor_xz": [13680, -4864], "yaw_raw": 3072, "result": 1, "when_event_flag_clear": 0x5D0, "arrival_message_index": 22}, {"player_xz": [12288, -2304], "actor_xz": [12160, -2304], "yaw_raw": 3072, "result": 2}]
	instance = {"stage": "ST0D", "spawn_set": set_id, "area_index": 0, "source_pc": "0x800eeb24", "record_ordinal": 0, "file_offset": offset(pointer), "source_record_ram": hex(pointer), "record_id": raw[1], "record_type": raw[2], "record_class": raw[3], "actor_class": raw[4], "resource_variant": raw[6], "resource_key": raw[7], "control": raw[8], "frame": raw[9], "native_private_raw": list(raw[8:12]), "source_bytes_hex": raw.hex(), "model_index": 9, "model_file": model_file, "identity": "Roll", "role": "roll_companion", "native_follower_profile": "tundra", "native_resource_flags": 0x6020, "transform_raw": [x, y, z, yaw], "transform": {"position": [-x / 256, -y / 256, z / 256], "yaw_raw": yaw, "yaw_turns": -yaw / 4096, "floor_height": True}, "native_pose_resolver": {"source": "ST0DT800EEB30..800EEC9C", "player_pose_key": "native_player_pose_raw", "cases": cases, "default": {"actor_xz": [x, z], "yaw_raw": yaw}}, "native_animation_startup": {"control": 0, "start_record": 0, "source_constructor": "0x800EBD78", "source_update": "0x800EB9BC"}, "native_hitbox": {"bounds_raw": list(struct.unpack_from("<6h", overlay, offset(0x800F0EFC))), "source_pointer_ram": "0x800f0efc", "source_field": "actor+0x58", "source_constructor": "0x800ebd78", "source_consumer": "GAME800B13B4/800B3564", "anchor": "actor+0x10"}, "native_interaction": {"stage": "ST0D", "actor_class": 96, "actor_state": 0, "actor_callback": "0x800eb9bc", "request_call": "0x800ec138", "request_api": "0x800BE2E0", "request_kind": 0, "message_call": "0x800BDCF8", "message_index": raw[11], "index_source": "unsigned actor+0x0F, dynamically selected by the native companion controller", "window": 0, "bank_id": "0x8010C000", "source_record_ram": hex(pointer), "target_descriptor_raw": list(struct.unpack_from("<6h", overlay, offset(0x800F0F08))), "target_descriptor_source": "0x800f0f08", "target_flags60": 3, "target_selector_source": "GAME800CC2F0/800CC5B4", "target_criteria": {"range_extra_raw": 192, "yaw_half_cone_raw": 512, "strict_bounds": True, "descriptor_xyz_rotated": False, "score": "integer3Ddistance+(absYawDelta>>2)", "line_of_sight": False}}, "native_following": {"idle_control": 0, "walk_control": 1, "run_control": 2, "walk_stop_control": 5, "run_stop_control": 6, "idle_start_distance_raw": 512, "walk_stop_distance_raw": 256, "walk_run_distance_raw": 1024, "run_stop_distance_raw": 512, "walk_speed_raw": 128, "run_speed_raw": 384, "walk_turn_raw": 64, "run_turn_raw": 96, "run_turn_while_player_moving_raw": 48, "source": "ST0DT800EC1E4/800EC288/800EC4A4", "unported": ["Combat, damage and scripted reaction states"]}}
	manifest["spawn_sets"] = [entry for entry in manifest.get("spawn_sets", []) if entry["id"] != set_id] + [spawn]; manifest["instances"] = [entry for entry in manifest.get("instances", []) if entry.get("spawn_set") != set_id] + [instance]; manifest["models"] = [entry for entry in manifest.get("models", []) if entry.get("model_index") != 9] + [model]
	manifest["source"]["native_tundra_follower"] = {"record": hex(pointer), "overlay_sha256": sha256(overlay), "model_flags": "0x6020", "callback": "0x800EB9BC", "constructor": "0x800EBD78", "spawn_predicate": "area0, scenario0, flag5E1 set, flag5E2 clear"}
	write_if_changed(output_dir / "scripted_actors.json", json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"); return manifest
